import { school, courses, gallery, pages } from './content.mjs';
export const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const external = (url, text, cls = 'text-link') => `<a class="${cls}" href="${esc(url)}" target="_blank" rel="noopener noreferrer">${text}<span class="sr-only"> (abre em nova aba)</span></a>`;
export const button = (text, options = {}) => options.href ? `<a class="button ${options.class ?? ''}" href="${options.href}">${text}</a>` : `<button class="button ${options.class ?? ''}" type="button" data-contact="${esc(options.contact ?? 'whatsapp')}"${options.course ? ` data-course="${esc(options.course)}"` : ''}>${text}</button>`;
export const eyebrow = text => `<p class="eyebrow">${text}</p>`;
export const heading = (label, title, text = '') => `<div class="section-heading reveal">${eyebrow(label)}<h2>${title}</h2>${text ? `<p>${text}</p>` : ''}</div>`;
export const mapUrl = `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(school.address.join(', '))}`;
export const address = () => `<address><strong>${school.address[0]}</strong><span>${school.address[1]}</span><span class="address-complement">${school.address[2]}</span></address>`;
export const header = current => `<a class="skip-link" href="#conteudo">Pular para o conteúdo</a><header class="site-header"><div class="header-inner"><a class="wordmark" href="/" aria-label="Arte Sobre as Cordas — Início"><img src="/assets/logo.webp" width="58" height="58" alt=""><span>Arte Sobre as Cordas<small>ESCOLA DE MÚSICA</small></span></a><nav class="desktop-nav" aria-label="Navegação principal">${pages.filter(p => ['/a-escola','/cursos','/aulas-online','/rota-musical'].includes(p.path)).map(p => `<a href="${p.path}"${p.path === current ? ' aria-current="page"' : ''}>${p.label}</a>`).join('')}<div class="nav-more"><button type="button" class="more-toggle" aria-expanded="false" aria-controls="more-nav">Mais <span aria-hidden="true">⌄</span></button><div id="more-nav" class="more-panel">${pages.filter(p => ['/eventos','/galeria','/contato'].includes(p.path)).map(p => `<a href="${p.path}"${p.path === current ? ' aria-current="page"' : ''}>${p.label}</a>`).join('')}</div></div></nav>${button('Aula experimental',{class:'small header-cta'})}<button class="menu-toggle" type="button" aria-label="Abrir menu" aria-expanded="false" aria-controls="mobile-nav"><span></span><span></span></button></div><nav id="mobile-nav" class="mobile-nav" aria-label="Navegação no celular">${pages.map(p => `<a href="${p.path}"${p.path === current ? ' aria-current="page"' : ''}>${p.label}</a>`).join('')}</nav></header>`;
export const footer = () => `<footer class="site-footer"><div class="container footer-top"><div class="footer-brand"><a class="footer-signature" href="/">Arte Sobre<br>as <em>Cordas.</em></a><p>Aprender. Sentir. Compartilhar.<br>A música faz parte da vida.</p></div><div><p class="footer-label">Explore</p><div class="footer-links">${pages.filter(p=>p.path!=='/').map(p=>`<a href="${p.path}">${p.label}</a>`).join('')}</div></div><div><p class="footer-label">Venha nos conhecer</p>${address()}${external(mapUrl,'Ver endereço no mapa')}<div class="social-links">${external(school.contacts.instagram,'Instagram')}<button type="button" data-contact="youtube">YouTube</button></div></div></div><div class="container footer-bottom"><span>© ${new Date().getFullYear()} Arte Sobre as Cordas</span><span>Desenvolvido para a escola · Blend Digital</span></div></footer>`;
export const modal = () => `<dialog id="contact-dialog" aria-labelledby="contact-title" aria-describedby="contact-description"><div class="dialog-content"><button type="button" class="close-dialog" aria-label="Fechar aviso">×</button><span class="dialog-note" aria-hidden="true">♪</span>${eyebrow('Vamos conversar')}<h2 id="contact-title">Em breve, mais perto.</h2><p id="contact-description">Estamos preparando este contato. O link oficial será disponibilizado em breve.</p><p class="dialog-context" hidden></p>${button('Entendi',{class:'close-action'})}</div></dialog>`;
export const pageIntro = (label,title,text,extra='') => `<section class="page-intro container">${eyebrow(label)}<h1>${title}</h1><p class="intro-text">${text}</p>${extra}</section>`;
export const invitation = () => `<section class="invitation wine"><div class="container invitation-inner reveal"><div>${eyebrow('Seu próximo acorde')}<h2>Sua história com a música<br>pode começar <em>aqui.</em></h2></div><div><p>Conheça a escola e dê o primeiro passo no seu tempo, do seu jeito.</p>${button('Agende uma aula experimental',{class:'light'})}</div></div></section>`;
export const courseCard = (c, index, compact=false) => `<article class="course-card reveal" id="${c.id}"><div class="course-visual visual-${c.image}" aria-hidden="true"><span class="course-number">${String(index+1).padStart(2,'0')}</span><img src="/assets/${c.image}.webp" alt="" width="520" height="360" loading="lazy"><span class="course-family">${c.family}</span></div><div class="course-body"><h${compact?'3':'2'}>${c.name}</h${compact?'3':'2'}><p>${c.description}</p><button type="button" class="text-link" data-contact="whatsapp" data-course="${c.name}">Consultar a escola<span class="sr-only"> sobre ${c.name}</span></button></div></article>`;
export const gallerySection = (full=false) => `<div class="gallery-grid">${(full ? gallery : gallery.slice(0,3)).map((g,i)=> {
 const content = g.image ? `<img src="${esc(g.image)}" alt="${esc(g.alt)}" width="700" height="800" loading="lazy">` : `<div class="gallery-placeholder placeholder-${i}"><span class="placeholder-lines" aria-hidden="true"></span><span class="placeholder-symbol" aria-hidden="true">${g.symbol}</span><span class="placeholder-caption">Histórias em ${i===0?'aprendizado':i===1?'cena':'movimento'}</span></div>`;
 return `<figure class="gallery-item reveal">${g.image && g.postUrl ? external(g.postUrl,content,'gallery-photo') : content}<figcaption><span>${g.category}</span><h${full?'2':'3'}>${g.caption}</h${full?'2':'3'}></figcaption></figure>`;
}).join('')}</div>`;
export const agendaNotice = () => `<div class="agenda-notice reveal"><span aria-hidden="true">♫</span><div><h3>Novos encontros estão por vir.</h3><p>A programação será divulgada após confirmação de datas, horários e locais.</p></div></div>`;
