import { school, courses, gallery, pages, courseImages } from './content.mjs';
export const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const external = (url, text, cls = 'text-link') => `<a class="${cls}" href="${esc(url)}" target="_blank" rel="noopener noreferrer">${text}<span class="sr-only"> (abre em nova aba)</span></a>`;
export const button = (text, options = {}) => options.href ? `<a class="button ${options.class ?? ''}" href="${options.href}">${text}</a>` : `<button class="button ${options.class ?? ''}" type="button" data-contact="${esc(options.contact ?? 'whatsapp')}"${options.course ? ` data-course="${esc(options.course)}"` : ''}>${text}</button>`;
export const eyebrow = text => `<p class="eyebrow">${text}</p>`;
export const heading = (label, title, text = '') => `<div class="section-heading reveal">${eyebrow(label)}<h2>${title}</h2>${text ? `<p>${text}</p>` : ''}</div>`;
export const mapUrl = `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(school.address.join(', '))}`;
export const address = () => `<address><strong>${school.address[0]}</strong><span>${school.address[1]}</span><span class="address-complement">${school.address[2]}</span></address>`;
export const header = current => `<a class="skip-link" href="#conteudo">Pular para o conteúdo</a><header class="site-header"><div class="header-inner"><a class="wordmark" href="/" aria-label="Arte Sobre as Cordas — Início"><img src="/assets/logo.webp" width="58" height="58" alt=""><span>Arte Sobre as Cordas<small>ESCOLA DE MÚSICA</small></span></a><nav class="desktop-nav" aria-label="Navegação principal">${pages.filter(p => ['/a-escola','/cursos','/suporte-ao-aluno','/rota-musical'].includes(p.path)).map(p => `<a href="${p.path}"${p.path === current ? ' aria-current="page"' : ''}>${p.label}</a>`).join('')}<div class="nav-more"><button type="button" class="more-toggle ${['/eventos','/galeria','/contato'].includes(current)?'is-current':''}" aria-label="Mais opções de navegação" aria-expanded="false" aria-controls="more-nav"><span class="more-dots" aria-hidden="true"><span></span><span></span><span></span></span></button><div id="more-nav" class="more-panel">${pages.filter(p => ['/eventos','/galeria','/contato'].includes(p.path)).map(p => `<a href="${p.path}"${p.path === current ? ' aria-current="page"' : ''}>${p.label}</a>`).join('')}</div></div></nav><button type="button" class="search-toggle" aria-label="Pesquisar no site" aria-haspopup="dialog" aria-controls="search-dialog"><svg viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></svg></button>${button('Aula experimental',{class:'small header-cta'})}<button class="menu-toggle" type="button" aria-label="Abrir menu" aria-expanded="false" aria-controls="mobile-nav"><span></span><span></span></button></div><nav id="mobile-nav" class="mobile-nav" aria-label="Navegação no celular">${pages.map(p => `<a href="${p.path}"${p.path === current ? ' aria-current="page"' : ''}>${p.label}</a>`).join('')}</nav></header>`;
export const footer = () => `<footer class="site-footer"><div class="container footer-top"><div class="footer-brand"><a class="footer-signature" href="/">Arte Sobre<br>as <em>Cordas.</em></a><p>Aprender. Sentir. Compartilhar.<br>A música faz parte da vida.</p></div><div><p class="footer-label">Explore</p><div class="footer-links">${pages.filter(p=>p.path!=='/').map(p=>`<a href="${p.path}">${p.label}</a>`).join('')}</div></div><div><p class="footer-label">Venha nos conhecer</p>${address()}${external(mapUrl,'Ver endereço no mapa')}<div class="social-links">${external(school.contacts.instagram,'Instagram')}<button type="button" data-contact="youtube">YouTube</button></div></div></div><div class="container footer-bottom"><span>© ${new Date().getFullYear()} Arte Sobre as Cordas</span><span>Desenvolvido para a escola · Blend Digital</span></div></footer>`;
export const modal = () => `<dialog id="contact-dialog" aria-labelledby="contact-title" aria-describedby="contact-description"><div class="dialog-content"><button type="button" class="close-dialog" aria-label="Fechar aviso">×</button><span class="dialog-note" aria-hidden="true">♪</span>${eyebrow('Vamos conversar')}<h2 id="contact-title">Em breve, mais perto.</h2><p id="contact-description">Estamos preparando este contato. O link oficial será disponibilizado em breve.</p><p class="dialog-context" hidden></p>${button('Entendi',{class:'close-action'})}</div></dialog>`;
export const pageIntro = (label,title,text,extra='') => `<section class="page-intro container">${eyebrow(label)}<h1>${title}</h1><p class="intro-text">${text}</p>${extra}</section>`;
export const invitation = (options = {}) => `<section class="invitation wine"><div class="container invitation-inner reveal"><div>${eyebrow(options.label ?? 'Seu próximo acorde')}<h2>${options.title ?? 'Sua história com a música<br>pode começar aqui.'}</h2></div><div><p>${options.text ?? 'Conheça a escola e dê o primeiro passo no seu tempo, do seu jeito.'}</p>${button(options.action ?? 'Agende uma aula experimental',{class:'light',course:options.action ? 'Conhecer a escola' : 'Aula experimental'})}</div></div></section>`;
export const courseCard = (c, index, compact=false) => `<article class="course-card reveal" id="${c.id}"><div class="course-visual visual-${c.image}" aria-hidden="true"><span class="course-number">${String(index+1).padStart(2,'0')}</span><img src="/assets/${c.image}.webp" alt="" width="${courseImages[c.image].width}" height="${courseImages[c.image].height}" srcset="/assets/${c.image}-640.webp 640w, /assets/${c.image}.webp ${courseImages[c.image].width}w" sizes="(max-width: 480px) calc(100vw - 40px), (max-width: 760px) calc((100vw - 57px) / 2), (max-width: 1060px) calc((100vw - 136px) / 3), 397px" loading="lazy"><span class="course-family">${c.family}</span></div><div class="course-body"><h${compact?'3':'2'}>${c.name}</h${compact?'3':'2'}><p>${c.description}</p><button type="button" class="text-link" data-contact="whatsapp" data-course="${c.name}">Consultar a escola<span class="sr-only"> sobre ${c.name}</span></button></div></article>`;
export const gallerySection = (full=false) => `<div class="gallery-grid">${(full ? gallery : gallery.slice(0,3)).map((g,i)=> {
 const content = g.image ? `<img src="${esc(g.image)}" alt="${esc(g.alt)}" width="700" height="800" loading="lazy">` : `<div class="gallery-placeholder placeholder-${i}"><span class="placeholder-lines" aria-hidden="true"></span><span class="placeholder-symbol" aria-hidden="true">${g.symbol}</span><span class="placeholder-caption">Histórias em ${i===0?'aprendizado':i===1?'cena':'movimento'}</span></div>`;
 return `<figure class="gallery-item reveal" data-category="${esc(g.category)}">${g.image && g.postUrl ? external(g.postUrl,content,'gallery-photo') : content}<figcaption><span>${g.category}</span><h${full?'2':'3'}>${g.caption}</h${full?'2':'3'}></figcaption></figure>`;
}).join('')}</div>`;
export const agendaNotice = () => `<div class="agenda-notice reveal"><span aria-hidden="true">♫</span><div><h3>Novos encontros estão por vir.</h3><p>A programação será divulgada após confirmação de datas, horários e locais.</p></div></div>`;
export const guitarFeature = () => `<article class="course-feature reveal"><div class="course-visual visual-violao" aria-hidden="true"><img src="/assets/violao.webp" alt="" width="1095" height="730" srcset="/assets/violao-640.webp 640w, /assets/violao.webp 1095w" sizes="(max-width: 1060px) calc(100vw - 84px), 430px" loading="eager" fetchpriority="high"><span class="course-family">Cordas</span></div><div class="course-feature-body">${eyebrow('Duas formas de explorar')}<h2>Violão</h2><div class="course-modalities">${courses.filter(c => c.image === 'violao').map(c => `<section id="${c.id}"><h3>${c.name}</h3><p>${c.description}</p><button class="text-link" type="button" data-contact="whatsapp" data-course="${c.name}">Consultar ${c.name.toLowerCase()}</button></section>`).join('')}</div></div></article>`;

export const searchModal = () => `<dialog id="search-dialog" aria-labelledby="search-title"><div class="search-content"><button type="button" class="search-close" aria-label="Fechar pesquisa">×</button>${eyebrow('Encontre seu caminho')}<h2 id="search-title">O que você procura?</h2><form role="search" id="site-search"><label for="search-input">Pesquisar no site</label><input id="search-input" name="q" type="search" placeholder="Ex.: violão, suporte, Rota Musical" autocomplete="off" maxlength="120"><button class="button" type="submit">Pesquisar</button></form><p id="search-status" role="status" aria-live="polite"></p><ul id="search-results" aria-label="Resultados da pesquisa"></ul></div></dialog>`;

export const discovery = () => `<section class="discovery section" id="descubra-seu-som"><div class="container discovery-grid"><div>${eyebrow('Seu primeiro compasso')}<h2>Comece pelo que<br>te faz <em>sentir.</em></h2><p>Uma música que você adora já pode ser um ponto de partida. Explore caminhos para encontrar seu instrumento.</p><span class="discovery-note" aria-hidden="true">♪</span></div><div class="discovery-panel"><fieldset><legend>O que você gostaria de experimentar?</legend><div class="discovery-options">${[['acompanhar','Tocar e acompanhar músicas'],['melodia','Explorar melodias e interpretação'],['voz','Usar minha voz e cantar']].map(([id,label],i)=>`<label><input type="radio" name="musical-interest" value="${id}"${i===0?' checked':''}><span>${label}<b aria-hidden="true"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6"><path d="M5 19 19 5M5 5h14v14"/></svg></b></span></label>`).join('')}</div></fieldset><div class="discovery-result" aria-live="polite"><p class="eyebrow">Um caminho para explorar</p><h3 id="discovery-title">Violão ou ukulele</h3><p id="discovery-description">Explore acordes, ritmos e o prazer de acompanhar as músicas que você gosta.</p><a id="discovery-link" class="text-link" href="/cursos/#violao-popular">Conheça estes instrumentos</a></div><p class="discovery-footnote">É um convite à descoberta. A escolha também depende do que você deseja aprender.</p><noscript><p><a class="text-link" href="/cursos/">Explore todos os instrumentos</a></p></noscript></div></div></section>`;
export const faq = () => `<section class="container section faq-section"><div>${eyebrow('Antes do primeiro acorde')}<h2>Vamos tirar<br>suas <em>dúvidas?</em></h2><p>Cada começo tem suas perguntas. A escola pode orientar você sobre os próximos passos.</p><a class="text-link" href="/contato/">Converse com a escola</a></div><div class="faq-list">${[
['Preciso já saber tocar?','Você pode procurar a escola para conversar sobre seu ponto de partida, seus interesses e as possibilidades de aprendizado. A proposta valoriza o processo de cada aluno.'],
['Como escolho meu instrumento?','Pense nas músicas que gosta de ouvir e no que deseja tocar ou cantar. Explore os cursos e converse com a escola para conhecer melhor as possibilidades.'],
['Como funciona a aula experimental?','A aula experimental é um convite para conhecer a escola. Formato, duração, disponibilidade e condições devem ser consultados com a escola.'],
['Preciso ter um instrumento em casa?','Converse com a escola antes de adquirir um instrumento. Os materiais necessários e as orientações para estudar em casa dependem do curso escolhido.'],
['Onde vejo as próximas apresentações?','A programação será divulgada na página de Eventos após a confirmação de datas, horários e locais. Você também pode acompanhar o Instagram da escola.']
].map(([q,a])=>`<details><summary>${q}<span aria-hidden="true">+</span></summary><p>${a}</p></details>`).join('')}</div></section>`;
